### ISSUE TITLE
TypeError: watchItems is not a function

### ISSUE THREAD

**Issue by andsm** [homerjam/angular-columnify#6]
at angular-columnify.js:271

```
$scope.$on('$destroy', function () {
    angular.element($window).off('resize', resize);

    watchItems();
    watchColumns();
});
```

Please, add check that the variables exists.

**Comment by homerjam** [comment]
Hi

Thanks for bringing this to my attention. I think this must be happening because the directive is being destroyed before being initialised (which happens on the next tick after compilation). It's likely that there's an issue somewhere else in your app causing this problem.

However, feel free to submit a PR - I think its a straightforward fix.

James

**Comment by andsm** [comment]
Yes, the problem is found. Removed unnecessary templateUrl.
Thanks!

```
        .state('posts', {
          parent: 'basePosts',
          url: '',
          templateUrl: 'posts.html',
          controller: ['$state', function ($state) {
            $state.go('groupPosts', {type: 'best'});
          }]
        })
```
